#!/usr/bin/env bash
# display information about subdomains.
dns_info () {

    if [ -z "$2" ]; then
	    subdomains=("www"  "lb-01" "web-01" "web-02")
	    for subdomain in "${subdomains[@]}"; do
		    dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, DOMAIN, "."); print "The subdomain " DOMAIN[1] " is a " $4 " record and points to " $5}'
	    done
    else
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, DOMAIN, "."); print "The subdomain " DOMAIN[1] " is a " $4 " record and points to " $5}'
    fi
}
dns_info "$1" "$2"
