#!/usr/bin/env bash
# Install nginx on your web-01

# Update package information then install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# enabe the most restrictive profile that will allow the traffic
sudo ufw allow 'Nginx HTTP'

# pass the content
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

#start nginx
service nginx start
