#!/usr/bin/env bash
#Install and Configure HAproxy so that it send traffic to web-01 and web-02

#update your system
sudo apt-get -y update && sudo apt-get -y upgrade

# Install HAproxy

 sudo apt-get -y install haproxy

# Configure Load Balancing
echo "
frontend http_front
    bind *:80
    mode http
    default_backend backend_servers


backend backend_servers
    balance roundrobin
    mode http
    server 227516-web-01 18.234.105.201:80 check
    server 227516-web-02 100.26.162.114:80 check " | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
# restart the HAProxy service
sudo systemctl restart haproxy
