#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080

sudo adduser nginx


sudo sed -i "s/#user www-data;/user nginx;/"  /etc/nginx/nginx.conf

sudo chmod 0644 /etc/nginx/nginx.conf

sudo sed -i "s/80 default_server/8080 default_server/"  /etc/nginx/sites-available/default

pkill apache2

#sudo service nginx restart
sudo -u nginx service nginx restart
