#!/usr/bin/env bash
# run as user
sudo adduser nginx
sudo sed -i "s/#user www-data;/user nginx;/"  /etc/nginx/nginx.conf
sudo chmod 0644 /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server/8080 default_server/"  /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
